[opcache]
; Enable Opcache
opcache.enable = 1
opcache.enable_cli = 0

; Memory
opcache.memory_consumption = 256
opcache.interned_strings_buffer = 16

; Validation
opcache.revalidate_freq = 60
opcache.validate_timestamps = 1

; Performance
opcache.max_accelerated_files = 10000
opcache.fast_shutdown = 1
opcache.enable_file_override = 1

; JIT compilation (PHP 8.0+)
opcache.jit = 1255
opcache.jit_buffer_size = 256M
