[supervisord]
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid
nodaemon=true
user=root

[program:php-fpm]
command=/usr/local/sbin/php-fpm
autostart=true
autorestart=true
stderr_logfile=/var/log/php-fpm.log
stdout_logfile=/var/log/php-fpm.log

[program:nginx]
command=/usr/sbin/nginx -g 'daemon off;'
autostart=true
autorestart=true
stderr_logfile=/var/log/nginx/error.log
stdout_logfile=/var/log/nginx/access.log

[program:queue-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /app/artisan queue:work database --sleep=3 --tries=3
autostart=true
autorestart=true
numprocs=1
stderr_logfile=/var/log/queue-worker.log
stdout_logfile=/var/log/queue-worker.log
